### ISSUE TITLE
Updating next.config.mjs Causes Node to Crash

### ISSUE THREAD

**Issue by otobot1** [celestemods-com/CelesteMods#531]
**Detailed Report**
Please see [this thread](https://nextjs-forum.com/post/1136363424218099902) from the [Next.js Discord](https://nextjs.org/discord). It is anonymized, but I am the OP, and one of their Discord Admins replied.

**Desktop (please complete the following information):**
* OS: [e.g. iOS]
    * Edition    Windows 10 Education
    * Version    22H2
    * Installed on    12/‎18/‎2022
    * OS build    19045.3208
    * Experience    Windows Feature Experience Pack 1000.19041.1000.0
 * Browser [e.g. chrome, safari]
     * Chrome
     * This is probably an exclusively server-side issue

**Next Steps**
1. Reproduce the issue on your local machine.
    * Start dev server (`npm run dev`).
    * Open `next.config.mjs`.
    * Make a change and save the config file.
    * When the file is saved, Node should crash.
2. Report issue in the [Next.js GitHub](https://github.com/vercel/next.js/issues).
    a. As per their [contribution guidelines](https://github.com/vercel/next.js/blob/canary/contributing.md), be sure to search existing [Issues](https://github.com/vercel/next.js/search?type=issues) and [Pull Requests](https://github.com/vercel/next.js/search?type=pullrequests) to make sure this isn't a duplicate report.
    b. Follow the steps in their [bug report template](https://github.com/vercel/next.js/issues/new?labels=template%3A+bug&template=1.bug_report.yml) to submit an issue.
3. Work with Next.js team to diagnose and resolve issue.

**Comment by otobot1** [comment]
@ShouvikGhosh2048 When you have a chance, would you mind seeing if you can reproduce this issue? I'd like to make sure it's not just my setup before I file a bug report.

**Comment by ShouvikGhosh2048** [comment]
@otobot1 
Yes, the issue occurs for me.
