### ISSUE TITLE
Mods Table Background Lighter Than Site Background

### ISSUE THREAD

**Issue by otobot1** [celestemods-com/CelesteMods#601]
**Describe the bug**
The background of the mods table component is lighter than the site background.

**To Reproduce**
This is most noticeable when the table is empty
1. Ensure SQL server is off, but Next.js server is on
2. Load `/mods`

**Expected behavior**
The mods table component should have the same background color as the page it's on. Avoid defining the color a second time. Either have the table inherit the color from the page, or have them both reference a value in the [consts folder](../tree/main/src/consts).

**Screenshots**
![image](https://github.com/celestemods-com/CelesteMods/assets/27628434/667793b4-3294-4720-b78a-4071029ebaad)

**Additional context**
Follow-up to #563.

**Comment by ShouvikGhosh2048** [comment]
The mods table has a different color only when its loading.

<img width="518" alt="table" src="https://github.com/celestemods-com/CelesteMods/assets/91585022/b7f6398f-14c3-4b53-a164-d69cf1789aec">

I think having the a different color while loading is fine. Thoughts?

**Comment by otobot1** [comment]
Agreed. I didn't realize it was just when loading.
