### ISSUE TITLE
Implement `useGamebananaModDownloadUrl`

### ISSUE THREAD

**Issue by otobot1** [celestemods-com/CelesteMods#603]
**Is your feature request related to a problem? Please describe.**
The 1-Click Install button currently always links to the home page.

**Describe the solution you'd like**
Implement [useGamebananaModDownloadUrl](../blob/main/src/hooks/gamebananaApi.ts#L252) so that the 1-Click Install button returns the same URL as the 1-Click Install button on GameBanana.

**Describe alternatives you've considered**
If this turns out not to be possible, we can just link to the mod's GameBanana page.

**Additional context**
Will need to reverse-engineer how the GameBanana URLs work. Follow-up to #563 item 5.

**Comment by otobot1** [comment]
I like the idea of using the mod search database - it's almost certainly more reliable than GamaBanana's API. I'll reach out to Maddie and make sure she doesn't mind if we start pinging it on the regular. We want to handle it server-side I think - that way we can easily cache the responses. Also, it looks like it also has screenshot URLs for each mod - we could use those in the carousel instead of the GB API.

**Comment by otobot1** [comment]
I was looking around her site, and apparently she maintains a [direct link service](https://maddie480.ovh/celeste/direct-link-service). Maybe we could use this instead. I'll have to have a think about what makes the most sense.

**Comment by otobot1** [comment]
@ShouvikGhosh2048 Have you started writing code for this? If not, I'd like to tackle it.

**Comment by ShouvikGhosh2048** [comment]
I haven't, you can work on this.
