### ISSUE TITLE
API Not Using `NODE_PUBLIC_BASE_PATH`

### ISSUE THREAD

**Issue by otobot1** [celestemods-com/CelesteMods#613]
**Describe the bug**
Based on the errors in my browser console, even with a non-empty `NODE_PUBLIC_BASE_PATH` specified, the tRPC client is still trying to fetch from a URL with an empty `BASE_PATH`.

**To Reproduce**
1. Checkout `production` branch.
2. Define a non-empty `NODE_PUBLIC_BASE_PATH`.
3. Run the `build` script.
4. Start the production server.
5. Try to load /mods. No mods will load - check browser console to see the URLs that it's trying.

**Expected behavior**
The API should work with any `NODE_PUBLIC_BASE_PATH`.

**Screenshots**
![image](https://github.com/celestemods-com/CelesteMods/assets/27628434/79d79f02-579d-4255-b08f-e7846e5ea51f)

**Additional context**
The tRPC client is a thin wrapper around the React Query client (RQ). Apparently RQ doesn't gracefully handle a custom base_path, but I found a custom queryFn that supposedly works. I tried passing it through the tRPC wrapper [here](https://github.com/celestemods-com/CelesteMods/blob/production/src/utils/api.ts#L48-L62) but the issue didn't go away. I'm unsure if it's because it's not the right fix, or if it's because the fix isn't being properly applied to the underlying RQ client.

**Comment by ShouvikGhosh2048** [comment]
This seems to fix the issue.

```diff --git a/src/utils/api.ts b/src/utils/api.ts
index a999c9a..4985eb4 100644
--- a/src/utils/api.ts
+++ b/src/utils/api.ts
@@ -13,7 +13,7 @@ import superjson from "superjson";
 import { type AppRouter } from "~/server/api/root";

 const getBaseUrl = () => {
-  if (typeof window !== "undefined") return ""; // browser should use relative url
+  if (typeof window !== "undefined") return `${process.env.NEXT_PUBLIC_BASE_PATH}`; // browser should use relative url
   if (process.env.NODE_ENV === "production") return `https://celestemods.com${process.env.NEXT_PUBLIC_BASE_PATH}`;
   return `http://localhost:${process.env.PORT ?? 3000}${process.env.NEXT_PUBLIC_BASE_PATH}`; // dev SSR should use localhost
 };```

**Comment by otobot1** [comment]
🤦‍♂️ Thanks!
