### ISSUE TITLE
Adding Publisher to Mod Header Main Info

### ISSUE THREAD

**Issue by campbell-godfrey** [celestemods-com/CelesteMods#725]
**Is your feature request related to a problem? Please describe.**
Users need to be able to see the name of each mod's publisher when scrolling through mods.

**Describe the solution you'd like**
(Not the best solution) Condense #Maps into Type & make room for Publisher

**Describe alternatives you've considered**
A mapper icon that the user can hover over for Publisher / Publish Date text to pop up.

**Additional context**
The list of info will be quite horizontally cramped if Publisher name is crammed in and other sections are less wide. Publish Date may also be worth seeing in a mod's main header when scrolling through a large number of mods.

**Comment by otobot1** [comment]
I have some thoughts on how to accomplish this.
![image](https://github.com/celestemods-com/CelesteMods/assets/27628434/79c66190-fefe-4801-aafa-6d157eb8b42a)
I'll probably create a new detailed follow-up issue.

**Comment by otobot1** [comment]
Superseded by #739 and #740.
